### ISSUE TITLE
Crash on tapping the media/image preview

### ISSUE THREAD

**Issue by mbutz** [chrislacy/TweetLanes#431]
Best twitter client I have found so far! Thanks for the good work. What I especially like is the fact that even after a refresh you can continue reading the tweets where you started.

Unfortunately I experience reproducable crashes whenever I try to tap on the media preview image (which is a great feature!).

Don't know if that has been reported yet. But there is a (german) review at Google Play Store moaning the same issue.

**Comment by mcr42** [comment]
The problem isin GestureImageView.java:623, where
 GestureImageView.onCreateDrawableState(...)
throws an UnsupportedOperationException: Not supported
if mstrict is true.
I'm not certain whether this would be correct, but skipping this check and just returning 
super.onCreateDrawableState(...)
makes it work in the Emulator.

**Comment by mbutz** [comment]
Ok, thanks a lot. I guess I will have to install the latest version from Github, right? Havn't done that before, always used Goggle Play. But will try as soon as I have time to... Thanks again for looking into that.

**Comment by mcr42** [comment]
No, you don't. I received update 1.5.1 yesterday around the time of your comment, and it contains this fix.
No more crashes on my device... ;-)

**Comment by mbutz** [comment]
Great! Updated via app store and also got rid of the crashes. Gratefully closing this issue.
